name: CI
on:
  pull_request:
  push:
  workflow_dispatch:
permissions: {}
jobs:
  lint:
    name: Lint Repository
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: lint-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - name: Set up mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      - name: Run linters
        run: mise run check
        env:
          LINT: true
          GITHUB_TOKEN: ${{ github.token }}
